image: Visual Studio 2022

build_script:
  - ps: .\scripts\build.ps1 -UseMSBuild
  - ps: .\scripts\package.ps1

test: off
deploy: off

artifacts:
  - path: artifacts\Nexus-Shell-0.2.0-win-x64.zip
  - path: artifacts\Nexus-Shell-0.2.0-win-x64.zip.sha256
