<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Nexus.Runtime/Nexus.Runtime.csproj" />
    <Compile Include="../../src/Nexus.Core/FilesProcessJob.cs" Link="FilesProcessJob.cs" />
  </ItemGroup>
</Project>
